services:
  web:
    image: nginx:latest
    container_name: web
    restart: unless-stopped
    network_mode: "host"
    volumes:
      # Mount your local config directory to the Nginx config path
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount a local folder to serve files for testing 'root' or 'index'
      - ./nginx/www:/var/www/html:ro
    command: /bin/sh -c "nginx -g 'daemon off;'"
