http {

server {
    listen 9999;
    root /usr/share/nginx/web;

    error_page 404 /usr/share/nginx/web/404.html;
    error_page 500 502 503 504 /usr/share/nginx/web/50x.html;
    # This causes an internal redirect to the specified uri with the client request method changed to “GET” (for all methods other than “GET” and “HEAD”).

    location / {
        index index.html;
    }
}


server {
    listen 9999; # optional. defaults to 80
    root /usr/share/nginx/web_test;

    location / {
        index index.html;
    }
}

}
