events {} # Required section

http {
    #include       /etc/nginx/mime.types;
    #default_type  application/octet-stream;
    root   ./html;
    client_max_body_size 100000;

    types {}

    server {
        types {
            text/css css html;
        }

        listen       127.0.0.1;
        #server_name  localhost;

        error_page 300 home.html;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            types {
                text/html html;
            }
        }

        location /about {
            return 302 "/";
        }

        autoindex on;
        access_log /tmp/log.txt;

    }
}
