events {} # Required section

http {
    root /var/www/html;

    server {
        listen       9090;

        location / {
            root /home/hanane/response/nginx/www;
            index  index.html index.htm;
            autoindex on;
        }
    }

    server {
        listen       localhost:9091;

        location /about {
            index about.html index.html index.htm;
        }
    }
}
