events {}  # Required section

http {
    server {
        listen 127.0.0.1:8080;

        cgi_pass .py /usr/bin/python3;
        cgi_pass .sh /bin/bash;
        cgi_pass .php /usr/bin/php-cgi;

        location / {
            root var/www/website3;
            index test_website.py;
            methods GET POST;
            cgi_pass .py /bin/python3;
        }

        location /video {
            root var/www/website3;
            index video.mp4;
            autoindex on;
            methods GET;
        }

        location /delete {
            root var/www/upload/;
            index invalid;
            methods DELETE GET;
        }

        location /dire {
            root var/www;
            index invalid;
            methods GET POST;
            autoindex on;
        }

        location /upload {
            root var/www;
            index index.html;
            autoindex on;
            methods GET POST;
        }
    }

    server {
        listen 127.0.0.1:5052;

        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php;
        cgi_pass .sh /usr/bin/sh;

        location / {
            root ./var/www/;
            index index.html;
            autoindex on;
            methods GET;
        }

        location /cgi-bin {
            root ./var/www/cgi-bin/;
            index session.sh;
            autoindex on;
            methods GET POST;

            cgi_pass .sh /usr/bin/sh;
            cgi_pass .php /usr/bin/php;
            cgi_pass .py /usr/bin/python3;
        }
    }
}