#!/usr/bin/env python3
"""
Simple Python CGI Script for Testing
This script demonstrates CGI functionality in Webserv
"""

import os
import sys
from datetime import datetime

# CGI scripts must output proper HTTP headers
print("Content-Type: text/html")
print()  # Empty line separates headers from body

# Get CGI environment variables
request_method = os.environ.get('REQUEST_METHOD', 'UNKNOWN')
query_string = os.environ.get('QUERY_STRING', '')
content_length = os.environ.get('CONTENT_LENGTH', '0')
script_name = os.environ.get('SCRIPT_NAME', '')

# HTML output
print("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python CGI Test</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 { color: #2c3e50; }
        h2 { color: #34495e; margin-top: 30px; }
        .info-box {
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin: 10px 0;
        }
        .success { background: #d4edda; color: #155724; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #3498db;
            color: white;
        }
        .code {
            background: #2c3e50;
            color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🐍 Python CGI Test - Success!</h1>
        
        <div class="info-box success">
            <strong>✓ CGI is working correctly!</strong><br>
            This page was generated dynamically by a Python script.
        </div>
        
        <h2>Request Information</h2>
        <table>
            <tr>
                <th>Property</th>
                <th>Value</th>
            </tr>
            <tr>
                <td><strong>Request Method</strong></td>
                <td>{method}</td>
            </tr>
            <tr>
                <td><strong>Query String</strong></td>
                <td>{query}</td>
            </tr>
            <tr>
                <td><strong>Content Length</strong></td>
                <td>{length} bytes</td>
            </tr>
            <tr>
                <td><strong>Script Name</strong></td>
                <td>{script}</td>
            </tr>
            <tr>
                <td><strong>Current Time</strong></td>
                <td>{time}</td>
            </tr>
        </table>
        
        <h2>Environment Variables</h2>
        <div class="code">
""".format(
    method=request_method,
    query=query_string if query_string else '(none)',
    length=content_length,
    script=script_name,
    time=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
))

# Display all CGI environment variables
cgi_vars = [
    'REQUEST_METHOD', 'QUERY_STRING', 'CONTENT_TYPE', 'CONTENT_LENGTH',
    'SCRIPT_NAME', 'SCRIPT_FILENAME', 'REQUEST_URI', 'SERVER_PROTOCOL',
    'GATEWAY_INTERFACE', 'SERVER_SOFTWARE', 'REMOTE_ADDR', 'REMOTE_PORT',
    'SERVER_ADDR', 'SERVER_PORT', 'SERVER_NAME'
]

for var in cgi_vars:
    value = os.environ.get(var, '(not set)')
    print(f"{var}: {value}<br>")

# Read POST data if available
if request_method == 'POST' and int(content_length) > 0:
    post_data = sys.stdin.read(int(content_length))
    print(f"""
        </div>
        
        <h2>POST Data Received</h2>
        <div class="code">
            {post_data}
        </div>
    """)
else:
    print("</div>")

# Closing HTML
print("""
        <h2>Test Cases</h2>
        <div class="info-box">
            <p><strong>Try these URLs:</strong></p>
            <ul>
                <li><a href="?name=John&age=25">With query parameters</a></li>
                <li><a href="?test=hello">Simple query</a></li>
                <li><a href="?foo=bar&baz=qux">Multiple parameters</a></li>
            </ul>
        </div>
        
        <p style="text-align: center; margin-top: 40px; color: #7f8c8d;">
            <small>Generated by Python CGI | Webserv Project</small>
        </p>
    </div>
</body>
</html>
""")
